version: "3.9"
services:
  crewai:
    build:
      context: .
    volumes:
      - ./app:/app  # Bind host app directory to container
    ports:
      - "5000:5000"  # Map container's port to host
    tty: true        # Enable interactive mode for debugging
